name: openconcept
dependencies:
  - numpy==1.14
  - scipy==1.0.1
  - networkx==2.1
  - sphinx==1.8.5
  - sphinxcontrib-websupport==1.1.2
  - nose
  - hdf5
  - h5py
  - mock
  - pip
  - pip:
    - pytest
    - openmdao
    - six
    - sphinx_rtd_theme
    - redbaron
    - -e git+https://github.com/OpenMDAO/dymos.git@2243f2e8158e31e132782dc72c38ce4e9d47a1ad